apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
    - name: redis-app
      image: redis:alpine
      volumeMounts:
        - name: redis-data
          mountPath: /data/redis
  volumes:
    - name: redis-data
      emptyDir: {}
